version: 2
updates:
  - package-ecosystem: 'npm'
    directory: 'packages/cognito'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: 'packages/s3'
    schedule:
      interval: 'daily'      

  - package-ecosystem: 'npm'
    directory: 'packages/ses'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directory: 'packages/sqs'
    schedule:
      interval: 'daily'
